name: Test composite action
on:
  pull_request:
    paths:
      - 'action.yml'
  workflow_dispatch:    

jobs:
  test-composite-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: generate release notes for Falco 0.36.0
        id: generate
        uses: ./
        with:
          branch: master
          repo: falcosecurity/falco
          output: test.md
          milestone: '0.36.0'

      - name: show output file
        run: cat test.md
